### ISSUE TITLE
Career Advice - Dev job vs own business

### ISSUE THREAD

**Issue by parulagg27** [facebook-developer-circle-delhi/Ask-The-Community#10]
**A community member asks anonymously:**

" Its about a career advice. I have a small business where we teach students to learn science. But I am confused, that should I do a developer Job or be incharge of my business. 
I cannot do both as, leaving my business at this time means killing it. I have this worry that I might not be able to earn that much, whereas my friends are getting good packages I might be the only one left out. 
And I do have a lot of interest in tech too. I am a web developer. Any Suggestions to clear things a bit. "

**Comment by shubhamoy** [comment]
Peace of mind is essentially what matters at the end of our day and if you've it then you can always make money because there isn't any relation between your peace of mind and your bank balance. Every decision has its trade off.

**Comment by vigzmv** [comment]
One more thing to add up to the above answer.
You have a lot of time. There's no rush. You will have a lot of time to do everything you want. Life isn't going to end at age 30, 40 or even 50.

**Comment by atul9911** [comment]
Right now i am having 4 paths, Please help me to choose one
1) I am a developer in India's largest wallet company and earning enough to be stable
2) I am having really good devops and architectural knowledge and one of my friend wants to start a company with me where we will be providing managed services to other companies 
3) Block Chain
4) Prepare for interview
I am stuck up very badly and don't know which one to choose.

**Comment by saranshkataria** [comment]
One general piece of advice: Don't follow the hype train. Figure out what interests you the most and follow that to be happier in the longer run. Think long term instead of short-term goals

**Comment by parulagg27** [comment]
IMO, it's good to close this issue now.
