### ISSUE TITLE
Career Advice - Getting an Internship 

### ISSUE THREAD

**Issue by parulagg27** [facebook-developer-circle-delhi/Ask-The-Community#11]
**A community member asks anonymously:**

"How to prepare and get summer internship 2019 at good startups like Paytm,etc? i'll be graduating in 202) . i'm interested in JS and blockchain. "

**Comment by tannishk** [comment]
Whats your college internships unfortunately depends a lot on it. Try to join @codingninjas or @codingelements . Do open source contribution . Do some projects . 

After all these try for GSOC or small startups if you are not from Tier 1 college . 
Post these steps you are good to go

**Comment by parulagg27** [comment]
Hi @tannishk. Thank you for your answer. 
But, one thing I **must** clarify, these questions were aksed by other members from group via that form link. And I'm only helping out in moderting by opening issues here to keep them anonymous. So, better would be, if you keep your answer generalised as per question without referring to me. Thanks :)

**Comment by gargankit90** [comment]
I would say do some projects in areas where you want internship.
Prepare for internship interviews, Hackerrank is a good site to begin with and then try leetcode.com

**Comment by parulagg27** [comment]
@codeb1ooded, would you like to add something?

**Comment by codeb1ooded** [comment]
As you have already mentioned your interest, I would advise you to gain some expertise on them by reading blogs about them, doing some projects and also, contributing to related open-source projects.
If you are considering companies like Paytm, then make sure you have strong data structures and basics.

**Comment by parulagg27** [comment]
Great! IMO, We've got some satisfactory answers. Closing this issue now. :)
