### ISSUE TITLE
Putting a progress bar on a website while uploading docs

### ISSUE THREAD

**Issue by parulagg27** [facebook-developer-circle-delhi/Ask-The-Community#12]
**A community member asks anonymously:**

" I am using angular 1.5 for my project and has a bootstrap datetime, when I am selecting a date it is not getting close. 
And second I need to put a progress bar while uploading docs, how can I achieve that "

**Comment by aakashrstg00** [comment]
Try using AngularJS Material the next time you have any feature requirement in an angularJs project.
For now, did you make a directive for the datepicker component or are you using it directly?

**Comment by saranshkataria** [comment]
We will need the code or something to tell about why the datepicker is not closing. For the progress bar, there are multiple ways of achieving it, html5 also added an inbuilt one. So some more specifics would be required for that as well

**Comment by parulagg27** [comment]
Alright! I think it's better to close this issue now, since it's been a long time &  I didn't get any response, regarding more details, from the person who asked this question.
