### ISSUE TITLE
Guidance for  Studying Abroad

### ISSUE THREAD

**Issue by parulagg27** [facebook-developer-circle-delhi/Ask-The-Community#14]
**A community member asks anonymously:**

" Currently I'm in 3rd year. I  can't figure out which option should I opt right now after my btech . I can do further studies But the primary issue is to pay fees for higher education as its difficult for my parents to afford that much expensive tuition fees of my btech. That's why , I'm skipping the option of further studies just after the btech. I m thinking to do job and save some money and go for higher studies but I m really fascinated to study in abroad .
So I have two questions basically 
1.The plan that I chose to follow would be correct?
2.To study in abroad basically M.S.what is the procedure to apply and what are the prerequisites that are required to study abroad specially in America and one more thing How can I get funding for the same like is there any scholarship available to study in abroad?"

**Comment by shubhamoy** [comment]
Before going for further education, you should always figure out your passion. After that, you would be in a better position to answer your dilemma. Life is always a bag of mixed feelings. So just try figuring out your passion and improving your skillsets.

Finally, you can refer to studyabroad.shiksha.com which does have a lot to offer. Even they do offer free consultancy for popular study destinations. Also can guide you with the scholarship options.

**Comment by learner213** [comment]
I too had a similar query! Thank you whosoever asked it :blush:  
Would just like to add one more question. @shubhamoy sir, I'm also pursuing b.tech, and I'm able to manage time between my college days and doing coding and exploring tech field regularly and currently in 2nd year. But eventually start working for a third domain as well would become hectic. What's the right time to start preparing for  GRE. Also, do my development work and projects I'm working on will help me in any of the ways for getting selected, or should I start focussing more on GRE from now onwards. Also, if we are able to get good score in GRE, doesn't that already help us in getting scholarship/ fee concession or do we need to apply for scholarships individually?

**Comment by shubhamoy** [comment]
Impact of your work like the recognition it garners does make a difference. Our education system hasn't been updated for years, as a result, we tend to lack on various grounds. So what you might try is to evaluate yourself by any online platform and then start working parallelly in strengthening your foundational knowledge. GRE score is only a single metric. Foreign universities/countries do have various scholarships to offer.

**Comment by parulagg27** [comment]
Great! Closing this issue now. :)
