### ISSUE TITLE
Succeeding as a Frontend Developer

### ISSUE THREAD

**Issue by parulagg27** [facebook-developer-circle-delhi/Ask-The-Community#15]
**A community member asks anonymously:**

" I'm doing B.tech in computer science and its my 2nd year now. I have started Frontend development in my first year and learnt a lot of things including the ReactJS framework. But many times I hear from my friends that anyone can do WebD or there is no future of webD, even I can't focus on my competitive coding skills also. results I also loose my motivation. But I love doing frontend development. Please somehow guide me how can I continue doing it and how can I get success in the field of frontend developer"

**Comment by parulagg27** [comment]
I think @aakashrstg00 @manishekaneja @IamManchanda can help?

**Comment by shubhamoy** [comment]
The beauty of frontend is the design aspect(UI and UX). Since you're undergoing your major in computer science, so you'd get sufficient exposure to programming. The future of design has to offer endless possibilities. You can surely refer to some amazing books on design, my personal favorite is https://www.amazon.in/Universal-Principles-Design-Revised-Updated/dp/1592535879.

**Comment by aakashrstg00** [comment]
Thanks, @parulagg27 for the mention.
Saying that there is no future in Web Dev is simply wrong and there is a high chance that the person saying this has not even tried to look deep into it. and yes when they say that anyone can do Web Dev, they actually mean that the initial learning is comparatively easier compared to other fields like Android etc, but if you dive deep into it, it has its own complexities and that requires hard work and practice to get used to. If you love doing it, then you shouldn't care what others are saying. 
As you've said that you've learned React basics, I would suggest that you try other frameworks as well and advance with the one you are most comfortable in. For the UI and UX Design part, these courses are good according to me.
[Course 1](https://www.udemy.com/the-complete-app-design-course-ux-and-ui-design/)
[Course 2](https://www.udemy.com/ux-web-design-master-course-strategy-design-development/)
[Course 3](https://www.udemy.com/advanced-css-and-sass/)

All the best.

**Comment by parulagg27** [comment]
Also, there is this excellent [resource](https://medium.com/tech-tajawal/modern-frontend-developer-in-2018-4c2072fa2b9c), describing the roadmap for modern frontend devs, specially meant for those who are self taught. Definitely worth referring to down the path!  :)

**Comment by saranshkataria** [comment]
All the resources (if relevant) should be added in the community resources repo as well please!

**Comment by parulagg27** [comment]
IMO, it's good to close this issue now. :)
