### ISSUE TITLE
Where to submit Fb's non-security bugs apart from Bug bounty page?

### ISSUE THREAD

**Issue by parulagg27** [facebook-developer-circle-delhi/Ask-The-Community#16]
**A community member asks anonymously:**

" Where can we submit Facebook's non-security Bugs , as the Bug Bounty page is accepting non-security Bug but they are not considering it for the Bounty or further process."

**Comment by saranshkataria** [comment]
I don't think there is a bounty program for non-security bugs. Why would they have one?

**Comment by parulagg27** [comment]
IMO, it's good to close this issue now!
