### ISSUE TITLE
Django + React/Vue

### ISSUE THREAD

**Issue by aashutoshrathi** [facebook-developer-circle-delhi/Ask-The-Community#17]
I need resources for integration of Django with Front-end framework.
Also, some advice would be helpful. I have experience with Django.

**Comment by saranshkataria** [comment]
@aashutoshrathi refer to the resources here https://github.com/facebook-developer-circle-delhi/Community-Curated-Resources
Also, for any other resources related help, it would be better to open an issue in that repo. Closing this out.
