### ISSUE TITLE
Topics & Projects to be worked upon - to apply for tech companies & understand real life scenarios

### ISSUE THREAD

**Issue by parulagg27** [facebook-developer-circle-delhi/Ask-The-Community#18]
**A community member asks anonymously:**

" I left a non tech job to learn and start career in web dev(full stack JS). I have been since then following courses and building stuff while learning. I also joined a startup as intern but the platform and level they have worked on seems far from what I have learnt so far. (e.g:Strapi, elasticsearch,integrating third party portals etc). How do I prepare myself for such a level of  competence ? Any list of topics which one should be very clear of before applying for tech companies ? Any project(s) that you would suggest me to build to understand real life scenarios ? 

P.S: I know working as intern or full time is the best way to learn, but there are certain restrictions and so I am asking all of it here. "

**Comment by gaurav-gogia** [comment]
@shubhamoy, could use your ideas here :)

**Comment by shubhamoy** [comment]
First figure out your calling, are you a 9-to-5 guy/gal or a hustler looking for challenges. Tech companies essentially evaluate your problem-solving mindset and not only what all technologies you've worked upon.

Simply put as you progress in your career the tech stack will always change from project-to-project and company-to-company. You should really focus on getting your basics strong(Operating System, Computer Architecture, Networking, Data Structures & Algorithms, and DBMS).

Finally, I would again say listen to your heart and pursue what you feel, you're really passionate about.

**Comment by parulagg27** [comment]
Great answer @shubhamoy :) 
Closing this issue now.
