### ISSUE TITLE
Help regarding learning path

### ISSUE THREAD

**Issue by parulagg27** [facebook-developer-circle-delhi/Ask-The-Community#19]
**A community member asks anonymously:**

"What should I do now that I have completed an internship in my summer at a reputed company? I want to pursue some research in deep learning but many places take people with higher percentage. I also think of stopping coding for a while so that I can concentrate on my studies. I am also preparing for GRE. Any suggestions on what can and should I do? "

**Comment by shubhamoy** [comment]
Pursue your learnings and try to interact with fellow developers on SO and Github. Try contributing to existing projects on Github to evaluate your level of learning and build contact. Also, see if you can build a library/project and host it on Github.

If you believe in your skills and they're at par then don't worry about your marks.

**Comment by parulagg27** [comment]
Great, thanks! Closing this issue now.
