### ISSUE TITLE
Leave current job & explore Web dev?

### ISSUE THREAD

**Issue by parulagg27** [facebook-developer-circle-delhi/Ask-The-Community#20]
**A community member asks anonymously:**

" Hi All,
I am working in US healthcare industry as a Quality Auditor but my interest is in Web development. 
I was thinking from a long time to leave the job and get prepared for the Web Developer profile as I have completed my MCA .
I am not getting much time to learn and study  web development with my current job.
So I am thinking to leave the job but I am afraid ,if I will leave the job and will not get a chance to become a web developer in any company then what I will do.
Hence, I request you all to help me come out of dilemma & take this decision by giving your suggestions for my current condition. I have made some websites also in WordPress for my interest.
DesigningBrain.com
Pragofeliz.com
Awaiting your suggestions!"

**Comment by shubhamoy** [comment]
The web has evolved from the simple notion of a web developer to the role of frontend and backend developer. Now the frontend does have UI, UX, engineering roles. Same goes for the backend which has its own roles.

I am assuming that your role as a Quality Auditor must have given you a first-hand experience of ensuring things are as per the rulebook. So my suggestion is to use your existing knowledge in a generic sense along with diving deep and exploring the domain of web development to figure out the role suitable for you.

**Comment by parulagg27** [comment]
Alright! Closing this issue now.
