### ISSUE TITLE
Projects on deep learning and Computer Vision

### ISSUE THREAD

**Issue by adityak2920** [facebook-developer-circle-delhi/Ask-The-Community#21]
currently I am learning and exploring computer visison. I just have a simple question from where I can find some projects for internships on computer vision and also besides internship from where I can find projects on deep learning and computer Vision

**Comment by flaredragon** [comment]
Hey 
The best place to find internships at computer vision startups I would say is angel.co
Apart from that you can take ideas for projects from CS231's project page of Stanford University.There are some great projects they are working on!
