### ISSUE TITLE
Resolving trailing dot issue in website url

### ISSUE THREAD

**Issue by parulagg27** [facebook-developer-circle-delhi/Ask-The-Community#22]
**A community member asks anonymously:**

" How to resolve the trailling dot issue on website url, and what will be the best technique or method to check that your website is vulnerable or not ."

**Comment by saranshkataria** [comment]
Need more context on this. Trailing dots are by default a unix style convention and more can be read about it here: http://www.dns-sd.org/trailingdotsindomainnames.html
Need more context about how this is a vulnerability

**Comment by parulagg27** [comment]
Also, if you are interested in exploring more about web security and vulnerabilities, do checkout the tutorials here: https://www.hacker101.com/ 
Closing this issue now!
