### ISSUE TITLE
Go vs Rust for system level programming?

### ISSUE THREAD

**Issue by parulagg27** [facebook-developer-circle-delhi/Ask-The-Community#23]
**A community member asks anonymously:**

" Go vs Rust for system level programming? By that, I mean Forensic applications like forensic imaging, file carving etc..

What would make my life a little easier in terms of:
1. Tuning for performance
2. Ease of use/code (for this specific use case)
3. Community/Tutorial

This area is new for me and I've only done Web Dev in go prior to this. 

Thanks ^.^ "

**Comment by shubhamoy** [comment]
I've been programming for a good amount of time and get into situations where I've to make a choice. First, the driving factor is the community support and maturity level of the language. I could share one approach; start solving one simple forensic application with one language(say Go) and then solve it using Rust. Finally, compare the performance and ease.

**Comment by saranshkataria** [comment]
Totally agreed with what @shubhamoy  has suggested here. It makes more sense to try something in both the languages, read a small comparison of what differentiates both of them, figure out what features of those are critical for your needs and then make an informed decision on the basis of those. Syntax can be learnt quickly once you know the concepts and why you are choosing one over the other.

**Comment by parulagg27** [comment]
Great, thanks! Closing this issue now.
