### ISSUE TITLE
Networking  guidance

### ISSUE THREAD

**Issue by parulagg27** [facebook-developer-circle-delhi/Ask-The-Community#25]
**A community member asks anonymously:**

" I am 2018 B.Tech passout. I participated in GSoC with Redhat and also now GCI mentor. Now working as Java developer in not a well known but a product based company .I like Competitive coding, used to do in 3 rd year. I belong to local engineering's College so have nearly null people to learn and get advice from. How can I develop my network? And please suggest some good blog and resources to follow daily to keep myself updated "

**Comment by learner213** [comment]
I think, if you've done GSOC and you are also a GCI mentor, you already have such a great network of people globally( specially from India, hehe :P) to whom you can look up to while facing an issue with your code. No one will be going to spoonfeed you (sorry for that word if it sounds impolite) unless you'll make an effort on your own. 
But, if you want to have more personalized network, I think attending meetups by developer communities including devC and having a conversation with other devs is surely the best way as per my experience. According to me, people here in dev communities are awesome and they are eager to listen to your story and learn from your experiences. Anways, for a quicker response to your doubts, you always have an option to post them in the group. 
Regarding blogs and resources, I think they should be specific to the technologies you are interested in. Not sure about the links for general tech related updates.

**Comment by learner213** [comment]
Hey! Can someone please shed more light on how you all keep yourself updated with the latest happenings in the tech industry. I too have a similar issue. Any good websites/ blogposts worth that I can follow for this purpose? 
@saranshkataria @harshitjuneja @shubhamoy

**Comment by shubhamoy** [comment]
Hey!
Building your network simply means creating an impact which can only be achieved by either leading from the front (for instance; share your experiences of GSoC) or follow various active communities(participate in conversations online/offline).

As you're part of a product based company, so definitely you can explore the areas of design thinking, design sprint, product management, etc which would essentially allow you to explore the ecosystem of customer centric approaches.

**Comment by parulagg27** [comment]
Great! Closing this issue now.
