### ISSUE TITLE
Qualifying for ACM-ICPC

### ISSUE THREAD

**Issue by parulagg27** [facebook-developer-circle-delhi/Ask-The-Community#27]
**A community member asks anonymously:**

" How to qualify ACM-ICPC? What should be the approach or the topics one should really focus upon while preparing for? It would be helpful if someone can share their experience too. "

**Comment by parulagg27** [comment]
@jainaman224, can you shed some light over here?

**Comment by jainaman224** [comment]
Sure @parulagg27,
Let's start with my experience. I have started coding in my 2nd year of college (I didn't know any programming language before that). Then my seniors directed me towards competitive programming in 4th semester. I started practicing on CodeChef and CodeForces (I personally feel codechef long challenge is great way to start as you struggle with problems for 10 days) and with time my skills improved. I was able to qualify for onsite regionals in 2017 & 2018.

Keys to success:
1. Patience
2. Keep learning (Always go through the editorials of contest)

You can find list of topics [here](https://www.geeksforgeeks.org/how-to-prepare-for-acm-icpc). It is a long list but all you need to start and keep practicing.

You can also participate in other competitions like:-
1. Facebook hackercup at https://www.facebook.com/hackercup
2. Google codejam, kickstart, hash code at https://codingcompetitions.withgoogle.com
and various others like codechef snackdown, topcoder open, tcs codevita etc.

**Comment by parulagg27** [comment]
Thanks! Good to close this issue now.
