### ISSUE TITLE
Guidance for becoming GCI mentor

### ISSUE THREAD

**Issue by parulagg27** [facebook-developer-circle-delhi/Ask-The-Community#28]
**A community member asks anonymously:**

" How to become a GCI mentor ? Do we need to be an active contributor for that organization or do they interview the applicants."

**Comment by raghavpuri31** [comment]
Being Org Administrator and Mentor myself at AOSSIE, one of the participating organizations in GCI-18, I can say that it's highly important for one to regularly participate in the org's particular project that one wants to mentor. This ensures the organization that the person has deep understanding of the codebase of that project and will be able to mentor it. However, in some of the cases it is also possible that an org looks into profile/work/previous projects of a prospective mentor and allow it to mentor in GCI after discussion. But the latter one is rare.

**Comment by parulagg27** [comment]
Thanks for your insights, @raghavpuri31. 
Also, @vaibhavsingh97 @swatisingh45 would you guys would like to add something here?

**Comment by parulagg27** [comment]
Thank you for the insights, @raghavpuri31 
Closing this issue now.
