### ISSUE TITLE
Inclusion of projects in resume

### ISSUE THREAD

**Issue by gaurav-gogia** [facebook-developer-circle-delhi/Ask-The-Community#33]
**A community member asks anonymously:**

"Is it okay to not to include projects in my intern resume . Although i have a good knowledge about Machine Learning and Deep learning but i don't have any good projects , simply because i want to work on a real life project. Help appreciated."

**Comment by saranshkataria** [comment]
I would exclude them only if you have something else that is worth showcasing. If that is not the case, including them tells the recruiter that you have done atleast something that you are mentioning. Execution is more effective than saying you have learned something

**Comment by parulagg27** [comment]
Indeed! Closing this issue now.
