### ISSUE TITLE
Getting started with web development

### ISSUE THREAD

**Issue by gaurav-gogia** [facebook-developer-circle-delhi/Ask-The-Community#34]
**A community member asks anonymously:**

"I want to learn web development I know css and php and thinking of learning react so is there any pre requisite to learn react. Also I want to contribute on open source but don't know how to start ,any lead for this will be appreciated."

**Comment by saranshkataria** [comment]
https://github.com/facebook-developer-circle-delhi/Community-Curated-Resources/blob/master/ReactJS.md
This should be helpful in getting started. Some basics of javascript and ES6 are always helpful in getting started and you can always refer to other concepts as you gain mastery.

**Comment by parulagg27** [comment]
Also, if you want to get started with your open source contributions as you mentioned in your last question, checkout the issue #7, that was posted earlier addressing the same. 
Closing this issue now.
