### ISSUE TITLE
becoming community lead

### ISSUE THREAD

**Issue by gaurav-gogia** [facebook-developer-circle-delhi/Ask-The-Community#35]
**A community member asks anonymously:**

"I want to persue my  career as a lead to the community  and help in motivating others . How can  I be a mentor and lead a community for others . "

**Comment by saranshkataria** [comment]
So happy to see this post! A good first step would be to start building confidence. Not posting this as you, but asking this anonymously tells me that you are still afraid of going on a public platform. It is understandable that it takes some confidence to do that, but you have to start somewhere and this could be a good first step. Next up, I would start with smaller targets, helping a person out, online or in-person. Then mentor a couple of them and then go on and be a part of an existing community as a core team member, learn things and then if you feel like it, go and start one of your own! Happy to answer more specific questions if you have any.

**Comment by parulagg27** [comment]
Good to close this issue now!
