### ISSUE TITLE
Blockchain Pre-requisites and learning path

### ISSUE THREAD

**Issue by learner213** [facebook-developer-circle-delhi/Ask-The-Community#5]
Hi! I'm here again with my doubt :p 

I have good knowledge of Python, C++, HTML, CSS. But still not that good at data structures although( P.S: I'm just a fresher). After hailing through all available tech fields,  I'm most interested in exploring blockchain technology and wants to build a project on it. 
Are their any pre-requisites for the same? Do I need to know any other programming/ scripting language/ framework as well before starting? Please share any good resources as well to start with. Currently all the resources seems to be scattered everywhere, and I found some of them difficult to understand. And it's so time consuming to go through all of them.  
P.S.: There are still no resources added for learning blockchain in curated-resources repository.

**Comment by saranshkataria** [comment]
Added a resource for cryptocurrency in that repo. And it makes more sense to open this issue there if you want resources instead of here?

**Comment by gaurav-gogia** [comment]
Here are some of the things that I believe are important for BlockChain:
1. Linked Lists
2. Hashing Algorithms
3. Merkle Tree
4. Types of BlochChains: Private, Consortium, Public
5. BlockChain & CryptoCurrency (difference)
6. Proof of Stake/ Proof of Work & other methods of transaction validation.

There are more concepts like double spending but this should be more than enough to get you started. As for programming language that you can use. Here are following worth looking into:
1. GoLang
2. Solidity

The only tutorials I could find:
1. [Primer on Blockchain and Bitcoin: Fundamentals and Use Cases]( https://www.udemy.com/primer-on-blockchain-and-bitcoin/?couponCode=BLOCKCHAIN-FBG&siteID=i.IXi5qsT7c-yyD1v.BvQqOkHltLyR8UkA&LSNPUBID=i*IXi5qsT7c)
2. [Create Ethereum & Blockchain Applications Using Solidity](https://www.udemy.com/solidity/?couponCode=FREECOUPON&siteID=i.IXi5qsT7c-ymwxSV4gVvM4CJk53xDEOw&LSNPUBID=i*IXi5qsT7c)

Disclaimer: Above provided tutorials might not be high quality. I still haven't been able to find good tutorials related to BlockChain yet.

**Comment by saranshkataria** [comment]
@DesmondANIMUS add it in the community resources repo instead?

**Comment by gaurav-gogia** [comment]
@saranshkataria, I would but I'm not sure if they'll help or how long they'll be available for free. I wouldn't want to add bad resources.

**Comment by learner213** [comment]
Thanks a lot @DesmondANIMUS for such detailed insights and course links.  :blush: 
Besides, @saranshkataria I'll take care of this next time, but since I also wanted to know the pre-requisites, i.e., concepts/ languages I should know well before starting, I thought it's better to post it here. Closing this issue now.

**Comment by shubhamoy** [comment]
@learner213 

There are two aspects of getting indulged with blockchain, first being making use of the available resources, like, you can quickly spin up a blockchain project using ethereum, solidity, and the web3 library(check truffle). 

The second option is a bit tricky where you invest time in getting through with the concept of distributed systems, Byzantine generals' problem, Byzantine fault tolerance, working of torrents, and other theoretical topics. 

Anyways a theoretical clarity is a must but sometimes getting a quick start is helpful. Check this repo where I have tried to allow anyone to quick start with blockchain([https://github.com/shubhamoy/HelloEthereum](https://github.com/shubhamoy/HelloEthereum)).
