### ISSUE TITLE
Getting started with Open Source

### ISSUE THREAD

**Issue by parulagg27** [facebook-developer-circle-delhi/Ask-The-Community#7]
**A community member asked anonymously:**

"How to begin open source contribution"

**Comment by parulagg27** [comment]
First and foremost, you should be comfortable with using git and github. For that I believe, going through these two links thoroughly would suffice:
1. [Intro to git & github ](https://medium.com/@megha_code/introduction-to-git-and-github-3a3f9b7a7e39) - It's a really good blog written by @codeb1ooded
2. [try git tutorial](https://try.github.io/) - for detailed insights 

Then, you should explore and try contributing to some beginner level projects to get comfortable with work flow. I think, [Open Hatch](https://openhatch.org/) & [up-for-grabs](https://up-for-grabs.net/#/) will help you find such projects of your interest. 
Hope that helps!

**Comment by saranshkataria** [comment]
Also look for the "good first issue" and "beginner" level tags on issues on Github. Maintainers usually tag those issues to help first-timers! Remember, even a document fix can be a good first issue. All it takes is getting started and then keep getting deeper.

**Comment by IamManchanda** [comment]
There is a free *video learning* course by [udacity](https://in.udacity.com/course/how-to-use-git-and-github--ud775-india) too.

**Comment by parulagg27** [comment]
Alright, good to close this issue now. :)
