### ISSUE TITLE
Guidance for GSOC

### ISSUE THREAD

**Issue by parulagg27** [facebook-developer-circle-delhi/Ask-The-Community#8]
A community member asks anonymously:

"I am beginner to gsoc 2019. Help me proceed."

**Comment by parulagg27** [comment]
cc: @geekanamika @vaibhavsingh97 and other GSOCers in the community :P

**Comment by vaibhavsingh97** [comment]
I am not advertising but I have written already extensive answer : https://www.quora.com/How-do-I-prepare-for-the-Google-Summer-of-Code-GSoC/answer/Vaibhav-Singh-182?share=50900702&srid=zfNa

Also, not only me all also other gsocers written their blog to get into the journey of open source and participate in competition like GSOC 😀. If you are reading my answer than please do Google, do research before asking the question as there are lots of great answers out there. If you have specific question than I am happy to answer 😀

**Comment by parulagg27** [comment]
That's literally a very comprehensive answer @vaibhavsingh97, with detailed insights & explanations. Definitely covering almost all the doubts every beginner will ever encounter. :)
Closing this issue now.
