### ISSUE TITLE
 Cyber Forensics / Security - Career Advice 

### ISSUE THREAD

**Issue by parulagg27** [facebook-developer-circle-delhi/Ask-The-Community#9]
**A community member asks anonymously:**

" I'm trying to build my career in Cyber Forensics/Security either as an investigator/architect. I've joined Gujarat Forensic Sciences University for MSc but I'm not really sure what else I can try. 

I understand the importance of open source projects related to security(hopefully will be able to contribute in one some day) and internships. If someone has any leads or any information regarding Security Engineering, Secure Application Development or Forensics or anything around this domain please advice. 

I do realise that my question might have been a little too vague but that is because I do not have much knowledge in this field yet. I'm but an pathfinder, trying to explore, hoping to understand the unknown."

**Comment by saranshkataria** [comment]
@shubhamoy can shed some light on this I think?

**Comment by shubhamoy** [comment]
Hi,

The security domain is pretty huge, one needs to create a balance between their common sense and in-depth knowledge. I would request you to figure out your zeal; the area where you're able to find your flair.

Try to explore with the domain knowledge you have and follow this amazing website of Adrian Crenshaw([www.irongeek.com](http://www.irongeek.com)). Also, you can refer to Security Tube(the website currently showing HTTP 500, check the youtube channel).

Feel free to ask, in case I've missed something or you would like to know more.

**Comment by parulagg27** [comment]
IMO, question has been satisfactorily answered. Closing this issue now. :)
